name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 01ffe065-b5d6-4b75-b29f-52d4b38da2cc
          SONAR_TOKEN: 6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6
          args: >-
            -Dsonar.projectKey=examly-test_01ffe065-b5d6-4b75-b29f-52d4b38da2cc
            -Dsonar.organization=examly-test -Dsonar.sources=
            -Dsonar.verbose=true
